Repository frontity/saturn-theme, pull requests merged in 2018-08, with the labels that each got.

#65 Fixes error in Image component when `content` prop is undefined
  src/shared/components/Image/index.js
Labels: needs review, review

#67 Fixes this component not rendering on custom post type
  src/pwa/components/Post/Body.js
  src/pwa/components/Post/TagList.js
Labels: needs review, review

#68 Fixes styles in LazyAudio
  src/shared/components/LazyAudio/index.js
  src/shared/converters/audio.js
Labels: needs review, review

#72 Fixes the margin top in Column
  src/pwa/components/Contexts/Column.js
Labels: needs review, review

#76 Fixes LazyFacebook in AMP and adds support for Facebook embedded posts and fixes LazyVideo in AMP.
  src/shared/components/Content/index.js
  src/shared/components/HtmlToReactConverter/index.js
  src/shared/components/LazyFacebook/index.js
  src/shared/components/LazyFacebookIframe/index.js
  src/shared/components/LazyInstagram/index.js
  src/shared/components/LazyTweet/index.js
  src/shared/components/LazyVideo/index.js
  src/shared/converters/facebook.js
  src/shared/converters/facebookIframe.js
  src/shared/converters/index.js
Labels: needs review, review

#77 Fixes amp-iframe, ul, ol, and li tags in AMP
  src/shared/components/Content/index.js
  src/shared/components/LazyIframe/index.js
  src/shared/processors/index.js
  src/shared/processors/removeAmpListTypes.js
Labels: needs review, review

#79 Removes wp-embedded-content with a converter
  src/shared/converters/index.js
  src/shared/converters/removeWpEmbeddedContent.js
Labels: needs review, review

#83 Change SlotInjector to use strings and place carousels inside Content using slots
  src/pwa/components/ContentCarousel/index.js
  src/pwa/components/Contexts/Column.js
  src/pwa/components/List/index.js
  src/pwa/components/Media/index.js
  src/pwa/components/Theme/index.js
  src/shared/components/Content/index.js
  src/shared/components/HtmlToReactConverter/index.js
  src/shared/components/HtmlToReactConverter/injectSlots.js
  src/shared/components/SlotInjector/index.js
Labels: needs review, review

#84 Fixes Image and converter for incomplete src and srcset
  src/shared/components/Image/index.js
  src/shared/converters/image.js
Labels: needs review, review

#88 Adds config for new site to MyR footer
  src/amp/components/Theme/index.js
  src/pwa/components/Contexts/Column.js
  src/shared/components/MyRFooter/index.js
Labels: needs review, review

#92 Fixes react warnings about keys in html2react
  src/shared/components/HtmlToReactConverter/injectSlots.js
  src/shared/components/SlotInjector/index.js
Labels: needs review

#90 Adds support for resizable iframes
  package-lock.json
  src/shared/components/LazyIframe/index.js
  src/shared/components/Spinner/index.js
  src/shared/converters/iframe.js
Labels: needs review, review

#98 Fixes iframe styles
  src/shared/components/Content/index.js
  src/shared/components/LazyIframe/index.js
  src/shared/converters/iframe.js
Labels: needs review, review

#100 Fixes Media missing mstId prop
  src/pwa/components/Media/index.js
  src/shared/components/SlotInjector/index.js
Labels: in progress, needs review

#117 Changes text Worona for Frontity in MyR Footer,
  src/shared/components/MyRFooter/Powered.js
Labels: needs review, review

#118 Fixes col tag bug in AMP and refactors processors
  src/shared/components/HtmlToReactConverter/index.js
  src/shared/processors/index.js
  src/shared/processors/removeAmpColWidth.js
  src/shared/processors/removeAmpIds.js
  src/shared/processors/removeAmpListTypes.js
Labels: needs review, review

#119 Adds support for twitter videos
  src/shared/converters/twitter.js
Labels: needs review, review

#121 Fixes colors in LoadMore button
  src/pwa/components/FetchWaypoint/index.js
  src/shared/components/MyRFooter/Legal.js
  src/shared/components/MyRFooter/Powered.js
  src/shared/helpers/index.js
Labels: needs review, review

#124 Support iframe data-src attribute in youtube converter
  src/shared/converters/youtube.js
Labels: needs review, review

#125 feat(myr-footer): move footer settings to db
  src/amp/components/Theme/index.js
  src/pwa/components/Contexts/Column.js
  src/shared/components/MyRFooter/index.js
Labels: needs review, review

#129 Reduce animation time in the existing animations
  src/amp/components/Post/index.js
  src/pwa/components/Comments/index.js
  src/pwa/components/Contexts/Context.js
  src/pwa/components/ListBar/index.js
  src/pwa/components/Media/index.js
  src/pwa/components/Menu/index.js
  src/pwa/components/NotificationsButton/index.js
  src/pwa/components/NotificationsSwitch/index.js
  src/pwa/components/Post/index.js
  src/pwa/components/PostBar/index.js
  src/pwa/components/Share/ShareCopy.js
  src/pwa/components/Share/ShareTotal.js
  src/pwa/components/Share/index.js
  src/pwa/components/Slider/index.js
  src/shared/components/LazyAnimated/index.js
  src/shared/components/Post/SharedCount.js
  src/shared/helpers/index.js
  src/shared/styled/ShareBar/index.js
Labels: needs review, review
